config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: 'yoyakus#index'
  resources :yoyakus do
    # resources :orders, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/yoyaku.rb
class Yoyaku < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/yoyakus_controller.rb
class YoyakusController < ApplicationController
  def index
    @yoyakus = Yoyaku.all
    @yoyaku = Yoyaku.new
  end
  
  def new
    @yoyaku = Yoyaku.new
  end

  def show
    @yoyaku = Yoyaku.find(params[:id])
  end

  def create
    Yoyaku.create(yoyaku_parameter)
    redirect_to yoyakus_path
  end

  def destroy
    @yoyaku = Yoyaku.find(params[:id])
    @yoyaku.destroy
    redirect_to yoyakus_path, notice:"削除しました"
  end

  def edit
    @yoyaku = Yoyaku.find(params[:id])
  end

  def update
    @yoyaku = Yoyaku.find(params[:id])
    if @yoyaku.update(yoyaku_parameter)
      redirect_to yoyakus_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def yoyaku_parameter
    params.require(:yoyaku).permit(:title, :content, :start_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/yoyakus_helper.rb
module YoyakusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: '前月'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: '今月'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: '来月'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <time datetime="<%= start_date.strftime('%Y-%m') %>" class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></time>
  <br> 
    <nav class="month_name">
      <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: '今月'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title">
      <%= t('simple_calendar.week', default: 'Week') %>
      <%= calendar.week_number %>
      <% if calendar.number_of_weeks > 1 %>
        - <%= calendar.end_week %>
      <% end %>
    </span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/yoyakus/edit.html.erb
<%= form_with(model: @yoyaku, local: true) do |form| %>

  <div class="title">
    <div class="form-tag">予約内容</div>
    <%= form.text_field :title %>
  </div>


  <div class="content">
    <div class="form-tag">IDaa</div>
    <%= form.text_field :content %>
  </div>

    <div class="time">
    <div class="form-tag">時間</div>
    <%= form.datetime_select :start_time %>
  </div>

  <p>
  <strong>コメント</strong>
  <%= @yoyaku.start_time.strftime("%m-%d") %>
</p>


  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/yoyakus/index.html.erb
<div class="toppage">
<h2 class="top">＊-＊ 予約カレンダー ＊-＊</h2>
<div class="col-md-8">
<%= month_calendar events: @yoyakus do |date, yoyakus| %>
  <%= date.day %>

  <% yoyakus.each do |yoyaku| %>
<div class="calendar__yoyaku">
    <div>
      <%= link_to yoyaku.title, yoyaku %> 
    </div>
  <% end %>
<% end %>

<br>
<div class="row">
<div class="col-md-4">
	<div class="schedule">今後の予定一覧</div>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th>タイトル</th>
      <th>日程</th>
    </tr>
  </thead>

  <tbody>
    <% @yoyakus.each do |yoyaku| %>
      <tr>
        <td><%= link_to yoyaku.title , yoyaku %></td>
        <td><%= yoyaku.start_time.strftime("%m-%d") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p class="edit_table" id="notice"><%= notice %></p>
<%= form_with(model: @yoyaku, local: true) do |form| %>
  <div class="title">
    <div class="form-tag">予約内容</div>
    <%= form.text_field :title %>
  </div>

  <div class="content">
    <div class="form-tag">iD</div>
    <%= form.text_field :content %>
  </div>

    <div class="time">
    <div class="form-tag">時間</div>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="submit">
    <%= form.submit %>
  </div>
  <% end %>
  </div>
<br>

</div>
</div>
</div>

app/views/yoyakus/show.html.erb
<!--- 予約の詳細が確認できる画面 ログインユーザー--->
<p id="notice"><%= notice %></p>
<div class="show">
<p>
  <strong>予約内容</strong>
  <%= @yoyaku.title %>
</p>

<p>
  <strong>IDccc</strong>
  <%= @yoyaku.content %>
</p>

<p>
  <strong>日時</strong>
  <%= @yoyaku.start_time.strftime("%m-%d") %>
</p>

<p>
  <strong>コメント</strong>
  <%= @yoyaku.start_time.strftime("%m-%d") %>
</p>

<%= link_to '編集', edit_yoyaku_path(@yoyaku) %>
<%= link_to '消去',yoyaku_path(@yoyaku.id), method: :delete, data: { confirm: '本当に?' } %>
<%= link_to '戻る', yoyakus_path %>
</div>